#!/usr/bin/env python3
"""Generate src/emoji_data.rs — the static emoji catalog for mdrv-em.

Sources (fetched at generation time, results committed):
  * unicode emoji-test.txt   — the authoritative fully-qualified catalog
                               (codepoints, group, fallback name)
  * CLDR annotations{,Derived}/{loc}.xml — per-emoji name + keywords,
                               one locale file per supported locale

Usage: python3 scripts/gen_data.py [locale ...]   (default: en id)

The generated file is committed; this script only reruns when the emoji
version or locale list changes. The LLM description pass (describe.py)
extends the same table later — see scripts/templates/describe.md.
"""

from __future__ import annotations

import json
import re
import sys
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

EMOJI_TEST_URL = "https://www.unicode.org/Public/emoji/16.0/emoji-test.txt"
CLDR_RAW = "https://raw.githubusercontent.com/unicode-org/cldr/main/common"
ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "emoji_data.rs"
DATA = ROOT / "data"
DESC = DATA / "descriptions.json"  # describe.py output, merged if present


def fetch(url: str) -> str:
    print(f"  GET {url}")
    with urllib.request.urlopen(url, timeout=60) as r:
        return r.read().decode("utf-8")


def cp_key(chars: str) -> str:
    """Unicode characters → '1F44A-1F3FB' style hex key."""
    return "-".join(f"{ord(c):X}" for c in chars)


# ---- emoji-test.txt ---------------------------------------------------------


def parse_emoji_test(text: str) -> list[dict]:
    """Fully-qualified entries only, in file order (group headers included)."""
    group = subgroup = ""
    out: list[dict] = []
    seen: set[str] = set()
    for line in text.splitlines():
        if line.startswith("#"):
            s = line.strip()
            if s.startswith("# group:"):
                group = s.split(":", 1)[1].strip()
            elif s.startswith("# subgroup:"):
                subgroup = s.split(":", 1)[1].strip()
            continue
        if not line.strip():
            continue
        body, _, comment = line.partition("#")
        parts = [p.strip() for p in body.split(";", 1)]
        if len(parts) != 2:
            continue
        cps, status = parts
        if status != "fully-qualified":
            continue
        # Fallback name from the trailing comment: "# 😀 E0.6 grinning face"
        toks = comment.split()
        name_toks = [
            t for i, t in enumerate(toks) if i > 0 and not re.fullmatch(r"E\d+\.\d+", t)
        ]
        cp = "-".join(cps.split())  # full sequence = stable key
        if cp in seen:  # component-only dups across groups
            continue
        seen.add(cp)
        out.append(
            {
                "cps": cps.split(),
                "cp": cp,
                "group": group,
                "subgroup": subgroup,
                "test_name": " ".join(name_toks).lower(),
            }
        )
    return out


# ---- CLDR annotations -------------------------------------------------------


def parse_cldr(loc: str) -> dict[str, dict]:
    """cp -> {"name": str|None, "kws": [..]}; merges annotations + derived.

    The canonical name lives in the `tts="true"` annotation; the plain
    annotation is pure keywords (community synonyms included).
    """
    result: dict[str, dict] = {}
    for kind in ("annotations", "annotationsDerived"):
        xml = fetch(f"{CLDR_RAW}/{kind}/{loc}.xml")
        root = ET.fromstring(xml)
        for ann in root.iter("annotation"):
            cp = cp_key(ann.get("cp"))
            e = result.setdefault(cp, {"name": None, "kws": []})
            if ann.get("tts") == "true":
                if not e["name"]:
                    e["name"] = (ann.text or "").strip()
            else:
                for k in (ann.text or "").split("|"):
                    k = k.strip()
                    if k and k not in e["kws"]:
                        e["kws"].append(k)
    return result


# ---- codegen ----------------------------------------------------------------


def rust_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> None:
    locales = sys.argv[1:] or ["en", "id"]
    print(f"emoji-test.txt:")
    catalog = parse_emoji_test(fetch(EMOJI_TEST_URL))
    print(f"  {len(catalog)} fully-qualified emoji")

    per_loc: dict[str, dict[str, dict]] = {}
    for loc in locales:
        print(f"CLDR {loc}:")
        per_loc[loc] = parse_cldr(loc)
        print(f"  {len(per_loc[loc])} annotated")

    groups: list[str] = []
    for e in catalog:
        if e["group"] not in groups:
            groups.append(e["group"])

    lines: list[str] = [
        "// @generated by scripts/gen_data.py — do not edit by hand.",
        f"// Emoji {EMOJI_TEST_URL.rsplit('/', 1)[-1].removesuffix('.txt')}"
        f" + CLDR annotations ({', '.join(locales)}).",
        "",
        "/// One catalog entry. `kw_{en,id,...}` are CLDR keywords per locale;",
        "/// add a field + rerun the generator to support more locales.",
        "pub struct EmojiEntry {",
        "    /// Emoji as rendered text.",
        "    pub ch: &'static str,",
        "    /// First codepoint — stable key (recents, dedup).",
        "    pub cp: &'static str,",
        "    /// CLDR name (locale `en`), falling back to emoji-test.txt.",
        "    pub name: &'static str,",
        "    /// One-line usage description (describe.py batch); empty until",
        "    /// data/descriptions.json exists.",
        "    pub desc: &'static str,",
        "    /// Index into [`GROUPS`].",
        "    #[allow(dead_code)]",
        "    pub group: u8,",
    ]
    for loc in locales:
        lines.append(f"    pub kw_{loc.replace('-', '_')}: &'static [&'static str],")
    lines += [
        "}",
        "",
        "#[allow(dead_code)]",
        "pub const LOCALES: &[&str] = &["
        + ", ".join(rust_str(l) for l in locales)
        + "];",
        "",
        "#[allow(dead_code)]",
        "pub static GROUPS: &[&str] = &[",
    ]
    lines += [f"    {rust_str(g)}," for g in groups]
    lines += ["];", "", "pub static CATALOG: &[EmojiEntry] = &["]

    descs: dict[str, str] = {}
    if DESC.exists():
        descs = json.loads(DESC.read_text())
        print(f"descriptions.json: {len(descs)} merged")

    catalog_json: list[dict] = []
    n_named = 0
    for e in catalog:
        ch = "".join(chr(int(c, 16)) for c in e["cps"])
        cldr = per_loc["en"].get(e["cp"])
        name = (cldr["name"] if cldr and cldr["name"] else None) or e["test_name"]
        if cldr:
            n_named += 1
        gi = groups.index(e["group"])
        kw_map: dict[str, list[str]] = {}
        fields = [
            f"ch: {rust_str(ch)}",
            f"cp: {rust_str(e['cp'])}",
            f"name: {rust_str(name)}",
            f"desc: {rust_str(descs.get(e['cp'], ''))}",
            f"group: {gi}",
        ]
        for loc in locales:
            ann = per_loc[loc].get(e["cp"])
            kws = (ann["kws"] if ann else [])[:12]  # cap keyword noise
            kw_map[loc] = kws
            fields.append(
                f"kw_{loc.replace('-', '_')}: &["
                + ", ".join(rust_str(k) for k in kws)
                + "]"
            )
        lines.append("    EmojiEntry { " + ", ".join(fields) + " },")
        catalog_json.append(
            {
                "cp": e["cp"],
                "ch": ch,
                "name": name,
                "group": e["group"],
                "desc": descs.get(e["cp"], ""),
                **{f"kws_{loc}": kw_map[loc] for loc in locales},
            }
        )
    lines += ["];", ""]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    DATA.mkdir(parents=True, exist_ok=True)
    (DATA / "catalog.json").write_text(
        json.dumps(catalog_json, ensure_ascii=False, indent=1)
    )
    print(
        f"wrote {OUT} ({len(catalog)} entries, {n_named} CLDR-named, "
        f"{len(groups)} groups) + data/catalog.json"
    )


if __name__ == "__main__":
    main()
