use crate::emoji_data::{EmojiEntry, CATALOG};
use fastembed::{
    InitOptionsUserDefined, Pooling, QuantizationMode, TextEmbedding, TokenizerFiles,
    UserDefinedEmbeddingModel,
};

/// bge-small-en-v1.5 embedding width (must match gen_vectors).
pub const DIM: usize = 384;
/// bge v1.5 retrieval recipe: prefix queries, not passages.
const QUERY_PREFIX: &str = "Represent this sentence for searching relevant passages: ";

/// Case-insensitive keyword search over names + CLDR keywords.
/// `fallback_locales` extends matching beyond `en` (e.g. ["id"]).
pub fn search(query: &str, fallback_locales: &[String], max_results: usize) -> Vec<usize> {
    let q = query.trim().to_lowercase();
    if q.is_empty() {
        return Vec::new();
    }
    let mut hits: Vec<(usize, i32)> = CATALOG
        .iter()
        .enumerate()
        .filter_map(|(idx, e)| score(e, &q, fallback_locales).map(|s| (idx, s)))
        .collect();
    hits.sort_by(|a, b| {
        b.1.cmp(&a.1)
            .then(CATALOG[a.0].name.len().cmp(&CATALOG[b.0].name.len()))
    });
    hits.truncate(max_results);
    hits.into_iter().map(|(idx, _)| idx).collect()
}

/// Semantic engine: bge-small int8 ONNX embedded in the binary plus the
/// flat catalog vector table (generated by `cargo run --bin gen_vectors`).
/// Popular/brand terms ("youtube", "movie night") match without appearing
/// in CLDR keywords; exact keyword hits still rank on top via a blend.
pub struct Engine {
    model: TextEmbedding,
    /// CATALOG.len() * DIM, rows L2-normalized (dot == cosine).
    vectors: Vec<f32>,
}

impl Engine {
    /// Load the session from embedded bytes (~0.5s) and the vector table.
    pub fn new() -> Result<Self, String> {
        let model = UserDefinedEmbeddingModel::new(
            include_bytes!("../assets/model_quantized.onnx").to_vec(),
            TokenizerFiles {
                tokenizer_file: include_bytes!("../assets/tokenizer.json").to_vec(),
                config_file: include_bytes!("../assets/config.json").to_vec(),
                special_tokens_map_file: include_bytes!("../assets/special_tokens_map.json")
                    .to_vec(),
                tokenizer_config_file: include_bytes!("../assets/tokenizer_config.json").to_vec(),
            },
        )
        .with_pooling(Pooling::Cls)
        .with_quantization(QuantizationMode::Static);
        let model = TextEmbedding::try_new_from_user_defined(model, InitOptionsUserDefined::new())
            .map_err(|e| format!("onnx session: {e}"))?;
        let vectors: Vec<f32> = crate::vectors_data::VECTORS
            .chunks_exact(4)
            .map(|b| f32::from_le_bytes(b.try_into().unwrap()))
            .collect();
        if vectors.len() != CATALOG.len() * DIM {
            return Err(format!(
                "vectors.bin is stale: {} f32 for {} emoji × {DIM} — rerun gen_vectors",
                vectors.len(),
                CATALOG.len()
            ));
        }
        Ok(Self { model, vectors })
    }

    /// Blended semantic + keyword ranking. Empty result = caller falls
    /// back to pure keyword search.
    pub fn search(
        &mut self,
        query: &str,
        fallback_locales: &[String],
        max_results: usize,
    ) -> Vec<usize> {
        let q = query.trim().to_lowercase();
        if q.is_empty() {
            return Vec::new();
        }
        let Some(qv) = self.embed_query(&q) else {
            return search(&q, fallback_locales, max_results);
        };
        let mut scored: Vec<(usize, f32)> = CATALOG
            .iter()
            .enumerate()
            .map(|(idx, e)| {
                let emb = dot(&qv, &self.vectors[idx * DIM..(idx + 1) * DIM]);
                // keyword exactness nudges (≤ +0.25); semantics dominates
                let kw = score(e, &q, fallback_locales).unwrap_or(0);
                (idx, emb + kw as f32 / 400.0)
            })
            .collect();
        scored.sort_by(|a, b| {
            b.1.total_cmp(&a.1)
                .then(CATALOG[a.0].name.len().cmp(&CATALOG[b.0].name.len()))
        });
        scored.truncate(max_results);
        scored.into_iter().map(|(idx, _)| idx).collect()
    }

    fn embed_query(&mut self, q: &str) -> Option<Vec<f32>> {
        let mut out = self
            .model
            .embed([format!("{QUERY_PREFIX}{q}")], None)
            .ok()?;
        let mut v = out.pop()?;
        l2_normalize(&mut v);
        Some(v)
    }
}

/// Search request/response channel types for the worker thread.
pub type SearchReq = (u64, String);
pub type SearchResp = (u64, Vec<usize>);

/// Spawn the background search worker: it owns the ONNX session so query
/// embedding never blocks the UI thread. Requests are coalesced — the
/// worker always answers only the newest query.
pub fn spawn_worker(
    fallback_locales: Vec<String>,
    max_results: usize,
) -> (
    std::sync::mpsc::Sender<SearchReq>,
    std::sync::mpsc::Receiver<SearchResp>,
) {
    let (req_tx, req_rx) = std::sync::mpsc::channel::<SearchReq>();
    let (resp_tx, resp_rx) = std::sync::mpsc::channel::<SearchResp>();
    std::thread::Builder::new()
        .name("mdrv-em-search".into())
        .spawn(move || {
            let mut engine = match Engine::new() {
                Ok(e) => Some(e),
                Err(e) => {
                    eprintln!("mdrv-em: embeddings disabled ({e})");
                    None
                }
            };
            while let Ok((seq, q)) = req_rx.recv() {
                let mut latest = (seq, q);
                while let Ok(next) = req_rx.try_recv() {
                    latest = next;
                }
                let (seq, q) = latest;
                let results = match engine.as_mut() {
                    Some(e) => e.search(&q, &fallback_locales, max_results),
                    None => search(&q, &fallback_locales, max_results),
                };
                if resp_tx.send((seq, results)).is_err() {
                    return;
                }
            }
        })
        .expect("spawn search worker");
    (req_tx, resp_rx)
}

fn score(e: &EmojiEntry, q: &str, fallback_locales: &[String]) -> Option<i32> {
    let mut best: Option<i32> = None;
    let mut consider = |s: i32| {
        if best.is_none_or(|b| s > b) {
            best = Some(s);
        }
    };

    let name = e.name.to_lowercase();
    if name == q {
        consider(100);
    } else if name.starts_with(q) {
        consider(80);
    } else if name.split_whitespace().any(|w| w == q) {
        consider(70);
    } else if name.contains(q) {
        consider(60);
    }

    // Usage descriptions (describe.py batch) widen recall.
    let desc = e.desc.to_lowercase();
    if !desc.is_empty() {
        if desc.split_whitespace().any(|w| w == q) {
            consider(40);
        } else if desc.contains(q) {
            consider(35);
        }
    }

    // `en` keywords always participate; configured locales extend them.
    let mut locales: Vec<&str> = vec!["en"];
    locales.extend(fallback_locales.iter().map(|s| s.as_str()));
    for loc in locales {
        let Some(kws) = kws(e, loc) else { continue };
        for kw in kws {
            let kw = kw.to_lowercase();
            if kw == q {
                consider(70);
            } else if kw.split_whitespace().any(|w| w == q) {
                consider(55);
            } else if kw.contains(q) {
                consider(45);
            }
        }
    }

    best
}

fn kws<'a>(e: &'a EmojiEntry, loc: &str) -> Option<&'a [&'a str]> {
    match loc {
        "en" => Some(e.kw_en),
        "id" => Some(e.kw_id),
        _ => None,
    }
}

fn l2_normalize(v: &mut [f32]) {
    let n = v.iter().map(|x| x * x).sum::<f32>().sqrt();
    if n > 0.0 {
        for x in v {
            *x /= n;
        }
    }
}

fn dot(a: &[f32], b: &[f32]) -> f32 {
    a.iter().zip(b).map(|(x, y)| x * y).sum()
}

/// cp key -> catalog index, for recents lookups.
pub fn index_by_cp() -> std::collections::HashMap<String, usize> {
    CATALOG
        .iter()
        .enumerate()
        .map(|(idx, e)| (e.cp.to_string(), idx))
        .collect()
}
