//! Flat little-endian f32 embedding table for `CATALOG` (row i = CATALOG[i],
//! 384 dims, L2-normalized). Generated by `cargo run --bin gen_vectors`
//! (bge-small-en-v1.5, int8 ONNX) from data/catalog.json. Regenerate when
//! descriptions change (scripts/describe.py output).
pub static VECTORS: &[u8] = include_bytes!("vectors.bin");
